### ISSUE TITLE
it didn't not return string

### ISSUE THREAD

**Issue by hoa2ng** [bobthecow/Faker#11]
Hi,
I used 'created_at' => $faker->dateTimeThisYear($max = 'now') but value return is 

'created_at' => unserialize('O:8:"DateTime":3:{s:4:"date";s:19:"2015-01-02 14:21:22";s:13:"timezone_type";i:3;s:8:"timezone";s:13:"Europe/Berlin";}'),

could you please help me?

Thanks in advance

**Comment by bobthecow** [comment]
You probably want the other Faker.

https://github.com/fzaninotto/Faker
